### ISSUE TITLE
AA streaming broken: http 403 STREAM_ERROR_98

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/gmusicapi#137]
As of yesterday, two new params are required for AA streaming: `slt` and `sig`. Both need to be present and correct to stream, otherwise you'll get the 403.

It looks like slt is a psuedo-random salt, which gets hashed with the songid and a secret embedded in the source to result in sig.

**Comment by LudekStoklasa** [comment]
Hi all, the key "27f7313e-f75d-445a-ac99-56386a5fe879" seems no longer valid for the WebClient based on my tests. I am seeing 403. Does anyone have an idea what is the new key?

**Comment by simon-weber** [comment]
The webclient has since been deprecated in favor of the mobileclient, mostly because it's painful to maintain and has the same features.

Feel free to use this issue to organize, but I probably won't help much myself.

**Comment by LudekStoklasa** [comment]
I use the mobileclient as a temporal solution for content streaming (getting the streamURL), but using the mobileclient has a downside that at least one mobile device needs to be registered. With the web client I can use the own desktop device registered using MusicManager. 

I've written JS web client  (based on your WebClient + others stuff + reverse engineer of GPM) using OAuth2 (with Bearer token) and I am able to do everything (playlist sync/deletion, file upload/deletion), the streamURL seems to be the last TODO for me.

**Comment by simon-weber** [comment]
Nice. For oauth, I'm guessing you're using the skyjam scope + Google's own key? Last I had heard custom redirects still weren't supported, so I'd be happy to hear if you'd figured something else out.

https://github.com/simon-weber/gmusicapi/issues/137#issuecomment-20060625 looks like the best we've got as far as tracking down a new key.

**Comment by LudekStoklasa** [comment]
Re: OAuth: I used the advantage that my app is utilizing own UPnP server -- so I created own app in Goggle console and set redirect uri to http://localhost:my_port where I am receiving the authorization key (that I exchange for access_token and refresh_token).

Re: tracking down the key: Thanks, I will try to track it down. Interestingly when I 've been inspecting the network traffic directly in the Chrome (when using the Google's Play Music app) there was no sig/salt in the url params, but I am going to investigate it further.

**Comment by LudekStoklasa** [comment]
Google seems to
completely changed the web protocol to retrieve a stream url.  I 've been inspecting the network traffic directly in the Chrome (when using the Google's Play Music app) there was no sig/salt in the url params, but before the 'mplay?' request there seem to be another https://play.google.com/log?format=json&authuser=0 requests doing a magic that Chrome doesn't get 403 when using the 'mplay?' request later.  

BTW: If I could register mobile client same way as desktop then I would be happy with retrieving streamURL using mobile client. Looking into your MusicManager I see that you are using https://android.clients.google.com/upsj/upauth which adds a desktop client, I wonder whether adding another param (like devicetype) could register/create the mobile device to eliminate the step that users have to manually install and register GPM on an Android device?

**Comment by zsszatmari** [comment]
Where are you located? I use the web api daily, but (living in Hungary) haven't encountered the issue (yet...).

**Comment by LudekStoklasa** [comment]
I am from Czech Republic. Are you saying that GET to https://play.google.com/music/mplay? with the songid and slt/sig (based on SHA1 by 27f7313e-f75d-445a-ac99-56386a5fe879) works for you and you are not getting 403 ??  Additional headers are 'Authorization' Bearer with the token and 'X-Device-ID' of course.

**Comment by zsszatmari** [comment]
Something like that... 
I use mjck instead of songid for all access songs. But yes I am using that 27f7313e... key still.
I am not using Authorization Bearer OAuth-style tokens, instead I 'hijack' cookies from a web based login flow... Also I have no idea what the u and pt arguments do :) 

https://play.google.com/music/mplay?u=0&pt=e&mjck=...&slt=...&sig=...

**Comment by LudekStoklasa** [comment]
Hi, thanks for the tip with the cookies hijacking!
I think that it also explains why Chrome doesn't get 403 when requesting the URL without sig/salt. 
My guess is that with the hijacked cookies you don't need to use the sig/slt too?

I believe that Chrome gets the cookies by the /log?format=json&authuser=0 requests (Authorization SAPISIDHASH) that I mentioned, but I don't seem to be allowed to use this, because I am not a web browser.

Nevertheless the cookies hijacking is for me even the worse case than using the mobile client (current workaround), because it forces users to Sign In to the GPM in Chrome at first (and each time) to be able to stream URL using my desktop app.  With the mobile client the user just needs to use GPM in Android once. 

I guess that the ability to auto-register a mobile device will be what I am going to look for (if it is even possible?)

Anyway, thanks for the tips, it makes things much clearer now ;-)

**Comment by zsszatmari** [comment]
Hi, 

I definitely need sig/slt. Without it it doesn't work. Also, I don't really think that the /log requests are relevant, the cookies are fetched via the login flow's Set-Cookie headers.
 
It's still strange to me that there is a sudden difference between oauth and web based login regarding playback. Hmm.

> Nevertheless the cookies hijacking is for me even the worse case than using the mobile client (current workaround), because it forces users to Sign In to the GPM in Chrome at first (and each time) to be able to stream URL using my desktop app.

Not true. I just save the cookies to user keychain.

You can try if my approach works for you (your account, your physical location) by downloading my app from https://www.gearmusicplayer.com (there is a free trial).

Best,
Zsolt

**Comment by LudekStoklasa** [comment]
Hi,
thanks for sharing.

I found that sig/slt isn't needed at all once these four cookie headers (SSID, HSID, SID, sjsaid) are set, like this:
'Cookie: SSID=A6N2iSkJohw1RAXbV; HSID=AnhPA03892K0CN6pZ; SID=dgT4BCXah8qt89ds7tmCIjz6UCT6G7j57m9-hLvgFVNnNi4eGYeWzPAn6wjN3v-SVUnrNA.; sjsaid=7c4200b2-8808-4760-b2ae-206cfea6920e'
Then single songid params works to get the stream url (e.g. https://play.google.com/music/mplay?songid=97736b8e-eb85-3a90-b78a-72efd39b516e ).

I also found that e.g. if you hijack the Chrome's cookie then they are valid until you log on in another browser. i.e. If I log on in Firefox then the Chrome's cookie becomes invalid and I need to still the Firefox's cookies to get the stream url. I wonder whether you are seeing the same?

**Comment by zsszatmari** [comment]
Yes, sig/slt is definitely not needed (and never were, given you supply cookies) if you are playing songs user has uploaded him/herself. Those songs have an id containing hashes.
Sig/slt are needed for All Access songs (search, or even in the library but added from search/radio). In that case, use 'mjck' instead of 'songid'.

Gear's access definitely works regardless if I log in from another browser. Don't know what might be the difference. The 'xt' cookie also seems to be important to me, maybe that's the clue.

Re Edit 2: Yes, your assumption is correct.

**Comment by LudekStoklasa** [comment]
OK, thanks for the confirmations/clarifications!

I was quite surprised how easy it is to create/register a new Android device. All you need to do is to set up non-existing X-Device-ID header when requesting 'https://android.clients.google.com/music/mplay?
I guess that the workaround of using the mobile client is pretty acceptable for me now. (i.e. No need for a user interaction with mobile device).

**Comment by bkhall** [comment]
Been following this conversation...

Your statement below about when to use 'mjck' vs. 'songid' is new info for
me. Is there an easy way to tell from the data in query results which one
is should be?


On Mar 19, 2017 12:22 AM, "Zsolt Szatmári" <notifications@github.com> wrote:

Yes, sig/slt is definitely not needed (and never were, given you supply
cookies) if you are playing songs user has uploaded him/herself. Those
songs have an id containing hashes.
Sig/slt are needed for All Access songs (search, or even in the library but
added from search/radio). In that case, use 'mjck' instead of 'songid'.

Gear's access definitely works regardless if I log in from another browser.
Don't know what might be the difference. The 'xt' cookie also seems to be
important to me, maybe that's the clue.

Re Edit 2: Yes, your assumption is correct.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/simon-weber/gmusicapi/issues/137#issuecomment-287595366>,
or mute the thread

**Comment by zsszatmari** [comment]
If it contains a dash character ('-'), then it's a user uploaded song, you need songid. Otherwise, it's an All Access song. :)
