### ISSUE TITLE
Ensure highest quality upload is possible, whatever the user think it is.

### ISSUE THREAD

**Issue by lloeki** [simon-weber/gmusicapi#140]
I want to get the highest possible quality. Therefore, I want either:

- a match (giving me a clear 320kbps MP3), if a match exists, whatever the original format.
- an upload *without transcoding* for unmatched songs if they happen to be in MP3.

The current upload method has no way to opt out of transcoding and uploading the whole song. An argument to the function could enable transcoding only for sample matching. 

An additional, separate argument could also globally control the case of whether I prefer to match or upload MP3 files (i.e do I prefer my MP3s or Google's?) which is IMHO a user choice.

**Comment by thebigmunch** [comment]
So, I may end up making a pass at this. Trying to work out what the best param(s) to expose would be:

* transcode - All or nothing transcoding switch
* lossy_transcode - Enable/disable transcoding for lossy formats
* transcode - Enable/disable per file type/extension, possibly with "lossless", "lossy", and/or "best"/"smart" values for convenience

The third obviously offers the most control, but I'm wondering if it's useful enough to warrant its addition and exactly how extensive to make it.

**Comment by thebigmunch** [comment]
@simon-weber: I still believe, as I stated in IRC back when this issue was first posted, that this screams user code to me. It would be trivial to handle this and more before ever sending filepaths to the upload method for uploading; I've always had this planned for my own scripts but haven't gotten around to it yet. And, I believe it moves gmusicapi too far away from simply providing convenient access to the Google Music APIs and their functionality. Moreover, there is already a whole heap of code in the upload method (so much that there's a comment about it); I'm not sure adding more logic into it is a great idea.

That being said, if you still think something should be implemented in gmusicapi, I'd like to know what form you want it to take so I can take a crack at it.

**Comment by simon-weber** [comment]
> this screams user code to me

Yeah, agreed. How about the all/nothing transcoding switch? I think that gives user code the ability to do all the things discussed above (since otherwise there's no way to check for a match but not transcode).

**Comment by thebigmunch** [comment]
Sounds good to me.
