### ISSUE TITLE
Request: Python3 support?

### ISSUE THREAD

**Issue by p0lar-bear** [simon-weber/gmusicapi#247]
I use [rhythmbox-gmusic](http://github.com/nvbn/rhythmbox-gmusic) to stream Google Play via Rhythmbox while I'm at work. I recently upgraded my Ubuntu laptop to 14.04 Trusty and found that the Rhythmbox version offered in the repos is 3.x, which uses Python 3 under the hood. I'm refraining from upgrading my workstation for the time being.

I'm just wondering if there are any plans to update this API to support Python3? I realize it's not a simple task, especially considering that mutagen's maintainer seemed [very passionate about his disdain for Python3](https://code.google.com/p/mutagen/issues/detail?id=27). If it would help at all, in that thread it seems that someone forked mutagen and created [mutagenx](https://pypi.python.org/pypi/mutagenx/1.21) which works with py3k (also here on [GitHub](http://github.com/LordSputnik/mutagen)).

**Comment by tjstum** [comment]
I started to take a look at this last night. It doesn't look like it will be an enormous effort to have a single-source codebase for at least 2.7 and 3.4. Protobufs seem to be working fine when using the 3.0 preview version (which fixes the issue in their setup.py).

I do have some questions, though:
- Is it OK to add a dependency on the [future](http://python-future.org/) project (what I'm using at the moment)? Would something more like [six](https://pythonhosted.org/six/) be preferable?
- What's the goal for the supported versions? It's obviously easiest to say 2.7 and 3.4.
- I'm not super clear on how the protocol buffer compiler generated code should interact with this effort. Do you run some external process and then commit the output code? I did apply some fixes to the generated code, so I want to make sure that your existing workflow isn't unduly disrupted.

Of course, if there's an existing effort underway, I'm happy to contribute there/defer my efforts! Thanks.

**Comment by simon-weber** [comment]
Awesome; thanks for looking into this.

> What's the goal for the supported versions? It's obviously easiest to say 2.7 and 3.4.

:+1: I'm fine with dropping 2.6 support.

> Is it OK to add a dependency on the future project

I had only heard of six before this, but according to [future's faq](http://python-future.org/faq.html) they're the way to go if we're ok dropping support for old versions. Sounds reasonable to me!

> protocol buffer compiler generated code

Ah, interesting. I'd like to avoid any post-generation edits to that code if possible. My hope is that 2/3 protobuf will generate 2/3 compatible code, in which case we can just regenerate it and be done. Otherwise, we could always just check in 2 versions of that code.

**Comment by thebigmunch** [comment]
Yes, python-future is the way to go (<3). Going that way should make it trivial to support 2.6, 2.7, and 3.3+. At one point I was gonna do some work on this before the dependencies were all py3k compatible, but I didn't really have the time to do more than an initial audit. I could probably help out with the effort (if needed) now, since I'd like to get my scripts/wrapper targeting 3.3+ before some big upcoming changes anyway.

**Comment by thebigmunch** [comment]
As an aside, I'd like to hear what people think about switching from oauth2client to [requests-oauthlib](https://github.com/requests/requests-oauthlib). oauth2client is an over-engineered monstrosity that will never be change as responsively as needed. Why not take the opportunity to use the same beautiful API of the requests library already in use in the project?

**Comment by simon-weber** [comment]
>  I'd like to hear what people think about switching from oauth2client to requests-oauthlib

I don't have strong feelings either way (unless oauth2client is blocking py3 support, in which case we should go for it).

**Comment by thebigmunch** [comment]
Nah, though it was one of the things blocking it for a quite a while. Hopefully it's not a problem in the future. Maybe I'll check it out on some free time someday. The only blocker currently is protobufs 3 being released.

**Comment by thebigmunch** [comment]
@tjstum: I don't know exactly the process you've used/plan on using. Just doing a quick futurize with all the imports from python-future then cleaning up the import section for readability is kinda what I was thinking of as a base. Basically, you end up getting this boilerplate:
```python
from __future__ import (absolute_import, division,
                        print_function, unicode_literals)
from future import standard_library
standard_library.install_aliases()
from builtins import *
```
Not exactly best practice, but this prevents most contributors from having to think about the compat when working on things. I certainly wouldn't argue against using just what is needed either.

For sure there are things that need to be cleaned up afterward either way.

* If using the new division, there are a couple instances that should be swapped to using the // operator instead of the ugly func wrapper that python-future employs.
* The dict from python-future should be used in all cases to get view/iterator objects from its methods. So any creation of empty dicts should be ``dict()`` instead of ``{}`` and any comprehensions would need to be changed to ``dict(iterator)``.
* Last major thing I can think of off the top of my head is with unicode_literals (definitely should be), gotta make sure there aren't any literals that should be bytes lying around.

That's probably a good point to commit the initial phase of porting to a feature branch, open a pull request, and see how bad the tests get screwed up.

**Comment by tjstum** [comment]
Hey, here's what I've done so far:
 * Ran `python-futurize --stage1`. That actually didn't have a ton of changes
 * Ran `python-futurize --stage2`. That had a majority of the changes.
 * Fixed up things so that the testsuite passed on python 2.7

I did a couple of other mechanical fixes, and I've gotten the testsuite to run on python 3.4 (initially, it wouldn't even start). There are still failing tests, though. I also plan to go through all of the changes and review them to see what makes sense (I did notice some instances where it wanted to do `list(dict.items())` that just can stay calling `items()`)

I tend to be of the "import what you need" camp, but I also see your point about making it easier for future contributors. I've been using [tox](https://tox.readthedocs.org/en/latest/) to do testing, and that's been going pretty well. I would think that we would want Travis to run the same thing, but I'm not really that familiar with Travis, so I would appreciate any help there.

When I get home tonight, I'll push my branch to my clone and send a pull request so we can keep working on it.

**Comment by thebigmunch** [comment]
I'd wait to see what @simon-weber wants to do about the importing before opening any pull request, just because it can change a lot in the code. At least, unicode_literals should be used for compatibility (people should be writing Python 3 code that python-future/__future__ just makes work for Python 2) and print_function/division in the files they're used.

PS I wish the --all-imports option to futurize would group all the __future__ imports and not do the direct builtins imports when also doing the * import. Such a simple thing that shouldn't really need to be cleaned up afterward : (

**Comment by tjstum** [comment]
I figured that opening a pull request is the best way to share the changes, but I can also just send a link to the branch I push. I certainly don't expect that the branch gets merged in the state it would be when I push it this evening.

It turns out that I didn't need to use unicode_literals. I did have to import the old basestr so that the validations work in Python 3.4.

**Comment by thebigmunch** [comment]
Yes, you don't NEED to, but, if you don't, string literals will be different types on different versions when they really should be consistent between versions.

**Comment by tjstum** [comment]
OK, I pushed my branch. If you want to take a look:

The stage 1 transformations (purely cosmetic) are on tjstum/Unofficial-Google-Music-API@2f1375f
The stage 2 transformations and a few other things I applied (like using `raise_from`) are on  tjstum/Unofficial-Google-Music-API@e7792e3

**Comment by tjstum** [comment]
@thebigmunch, I thought more about your suggestions to install the standard boilerplate and __unicode__literals. I think I agree, since even though it makes the porting effort a bit more annoying, it is probably the right thing to do.

So far, progress has been coming along. I got some of the tests working (but after re-running python-futurize and installing the boilerplate, some of the python 2 tests broke). For right now, I'm not super focused on the code readability (I'm leaving the imports at the top as just the four lines), but I'll take a pass before submitting.

**Comment by tjstum** [comment]
This was done in https://github.com/simon-weber/gmusicapi/pull/398 and https://github.com/simon-weber/gmusicapi/pull/396

**Comment by simon-weber** [comment]
Ah, thanks; I'll close this.
