### ISSUE TITLE
'ndg-httpsclient' listed as a requirement in setup.py

### ISSUE THREAD

**Issue by juanrubio** [simon-weber/gmusicapi#364]
I'm wondering if this module is still in use in the project?

Also listed in gpsoauth's setup.py

Thanks,
Juan

**Comment by simon-weber** [comment]
Yes; it's required to support SNI, which Google uses on some of the subdomains we make requests to. There are more details at http://urllib3.readthedocs.org/en/latest/security.html#openssl-pyopenssl and an example of what happens when it's not installed in https://github.com/simon-weber/gmusicapi/issues/350#issuecomment-144499012.
