### ISSUE TITLE
investigate oauth support for mobileclient

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/gmusicapi#426]
I got a tip over email about true oauth support on the mobileclient. The gist of it is that we ought to test the `https://www.googleapis.com/auth/skyjam` scope with a custom redirect, then use it to auth the mobileclient.

This was found to not work in the past (https://github.com/simon-weber/gmusicapi/issues/290#issuecomment-68191741). But, the email also claimed that they had to switch from the `sj` scope to the `skyjam` scope recently, so google may have changed things on their end to accommodate this.

**Comment by bubbleguuum** [comment]
I did some oauth2 tests on Android with code  (in Java) that closely match the mobileclient.

The oauth2 flow on Android can be started using the GoogleAuthUtil.getToken() API. It displays a nice system consent screen asking user to "Access the Google Music Library". But any further API request 
using the oauth token results in a 403:

"error": {
		   "errors": [
		    {
		     "domain": "usageLimits",
		     "reason": "accessNotConfigured",
		     "message": "Access Not Configured.  has not been used in project xxxxxxxxxxxxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sj/overview?project=xxxxxxxxxxxxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
		     "extendedHelp": "https://console.developers.google.com/apis/api/sj/overview?project=xxxxxxxxxxxxxx"
		    }
		   ],
		   "code": 403,
		   "message": "Access Not Configured.  has not been used in project xxxxxxxxxxxxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sj/overview?project=xxxxxxxxxxxxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
		  }
		 }

If you follow the mentioned URL, you cannot enable the API for the app since the API is not public.
Not a surprise.
The GoogleAuthUtil oauth2 flow doesn't allow to override the client_id/client_secret and seems to derive one from the calling package, so I believe the only way is to have a standalone oauth2 flow similar to the iosclient branch, with the ability to use what seems to be the iOS Google Music app's client id and secret If I understand the iosclient source correctly (correct me if I'm wrong) 

Anyway, all of this to say that I have a strong hint that all mobile endpoints would work with an oauth2 token (Bearer Authorization header) rather than the current ClientLogin token (GoogleLogin Authorization header).

I've been looking at an alternative to GoogleLogin because some of my app users get a 401 "Unauthorized" errors (with a valid token) for the mobile device list endpoint for example. These 401 seems random (and for now unexplained) but seems more and more frequent, as if ClientLogin was progressively being deprecated...

**Comment by bkhall** [comment]
I’m using it successfully in my app with no issues using the “Bearer” header.

**Comment by bubbleguuum** [comment]
@bkhall : thank you for your response.

Can you successfully use the /sj/v1.11/devicemanagementinfo endpoint with that token without getting a 403 ?
Here's what I am doing to get the token, but the resulting token results in a 403:
'''
try {
			GoogleAuthUtil.getToken(this, account, "oauth2:https://www.googleapis.com/auth/skyjam");
		} catch (IOException | GoogleAuthException e) {
			if(e instanceof UserRecoverableAuthException) {
				startActivityForResult(((UserRecoverableAuthException) e).getIntent(), 4343);
			}
		}

**Comment by bkhall** [comment]
I don't use that one in my app, what's the full url?

**Comment by thebigmunch** [comment]
@bubbleguuum: You may also want to try with a newer api version; it's up to 2.4. Doubt it'll have an effect, but you never know.

**Comment by bubbleguuum** [comment]
@bkhall 

The full URL is https://mclients.googleapis.com/sj/v1.11/devicemanagementinfo.
I suppose you do not do any streaming in your app thus do not need a device id ?

@thebigmunch 

Same error with the 2.4 API

**Comment by bkhall** [comment]
Nope. I get a 403 also. In reality, I'm not hitting many of the urls you all are using. Since my app resides on the device, which usually has the actual Google Play Music app on it, I just run queries against their database to get the info I need, rather than making a network call.

It seems that the url for playing/streaming the songs lives on a different domain than the googleapis one, so that works just fine.

**Comment by bubbleguuum** [comment]
@bkhall  

Thanks for testing and confirming.
Now, the question is how to have the devicemanagementinfo working using oauth2. If it is at all possible. Or is there a way to get a valid device id differently ?

**Comment by bkhall** [comment]
Well, I've offered to mod my app to reveal the device_id to the user, which you could then enter manually in your client - might help with testing, but I don't think you'll want to call that a long term solution.

**Comment by sciencepro** [comment]
@bkhall Are you able to successfully stream tracks with the Android authentication method listed in your gist? I was using a similar method that worked until a few weeks ago, when requests made with those auth tokens started 401'ing.

`Bundle authResult = manager.getAuthToken(account, "sj", false, null, null).getResult();`

I just switched to yours, and I noticed that the auth prompt now has a nice description for Google Play Music. However, the auth tokens I'm getting still don't seem to work in ways that they used to. For example, here's a search request response I'm setting now using one of those tokens.

`{"error": "401 Client Error: Unauthorized\n(requests kwargs: {'url': 'https://mclients.googleapis.com/sj/v1.11/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'h', 'max-results': 15}, 'method': 'GET'})\n(response was: '{\\n \"error\": {\\n  \"errors\": [\\n   {\\n    \"domain\": \"global\",\\n    \"reason\": \"authError\",\\n    \"message\": \"Invalid Credentials\",\\n    \"locationType\": \"header\",\\n    \"location\": \"Authorization\"\\n   }\\n  ],\\n  \"code\": 401,\\n  \"message\": \"Invalid Credentials\"\\n }\\n}\\n')"}`

**Comment by bkhall** [comment]
Yes, I can stream just fine using the token retrieved from my gist. Nothing else in the API seems to work. The only endpoint I care about though is the streaming endpoint. All the other data, I get from the Google Play Music app database.

**Comment by denysvitali** [comment]
@bkhall What's the streaming endpoint you're using? I have tried with a generated token but nothing works

**Comment by bkhall** [comment]
This is my base streaming url:
https://android.clients.google.com/music/mplay?

Then depending on the id of the song, I append like this:
if (id.startsWith("T"))
    url.append("mjck=");
else
    url.append("songid=");

url.append(id).append(<other options>);

Then I run all that through the signing utility to get the final url.

I'm pretty sure you all do the same thing. I'm also pretty confident that you all may not be setting all the necessary headers properly, especially concerning device_id.

**Comment by simon-weber** [comment]
It looks like Google changed the ios client to use the mobileclient interface, and now normal mobileclient calls work with the skyjam scope. It seems to even work with custom projects and redirects.

I haven't tested very thoroughly yet, but this certainly looks promising.

**Comment by thebigmunch** [comment]
All the tests passed using OAuth for me btw : P

**Comment by simon-weber** [comment]
Hm, trying now, I can't replicate my success with a custom project. I get the accessNotConfigured 403.

Does anyone have a chance to take a second look?

**Comment by thebigmunch** [comment]
I've been super busy with other things. I never got around to finding a good way to support both forms of login for testing without making it a mess. Since I don't know when I'd actually have time again to work on that, so I'll just rebase and cleanup my changes with the tests left as-is. It's probably best for Simon to mess with that in case he wants to get CI ported over to OAuth2 as well.

**Comment by simon-weber** [comment]
I've got mobileclient oauth working by using the skyjam scope with Google's ios app credentials. Follow https://github.com/simon-weber/gmusicapi/issues/620#issuecomment-439731287 for details.

It doesn't look like new custom apps can be created, though, since the api has been marked "private" in the api console. Existing apps still seem to work (eg [Autoplaylists](https://autoplaylists.simon.codes/)).
