### ISSUE TITLE
playCount key missing 

### ISSUE THREAD

**Issue by dantespe** [simon-weber/gmusicapi#467]
There seems to be a bug in the Mobileclient.get_all_songs() function. It seems that songs that have never been played before sometimes do not have a key 'playCount.'

**Comment by simon-weber** [comment]
We're typically at the mercy of Google for reasonable schemas here. In this case, it looks like the field is expected to be optional in our internal schema: https://github.com/simon-weber/gmusicapi/blob/7c5b5db42c098304118df2e59032e17a5c223ed8/gmusicapi/protocol/mobileclient.py#L120.

Sorry that's not better documented! There's a longstanding ticket (https://github.com/simon-weber/gmusicapi/issues/258) to expose these rather than the simple examples that are in the docs now.
