### ISSUE TITLE
Can't install due to Openssl error on Windows

### ISSUE THREAD

**Issue by bulletfreak** [simon-weber/gmusicapi#470]
I don't know where else to post this so here. I'm unable to install this due to two of its dependencies requiring Openssl, which i installed, but it still won't work. It always throws me this error whenever i try to install either cryptography or pyOpenSSL `C:\Users\bulle\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcbuild\temp.win-amd64-2.7\Release\_openssl.c /Fobuild\temp.win-amd64-2.7\Release\build\temp.win-amd64-2.7\Release\_openssl.obj
_openssl.c
build\temp.win-amd64-2.7\Release\_openssl.c(423) : fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
error: command '"C:\Users\bulle\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe"' failed with exit status 2`

**Comment by simon-weber** [comment]
It looks like windows is having trouble finding openssl headers; are they in your path? [This post](https://social.msdn.microsoft.com/Forums/en-US/9c0cbc07-823a-4ea7-bf7f-e05e13c17fb2/fatal-error-c1083-cannot-open-include-file-opensslcryptoh-no-such-file-or-directory?forum=vcgeneral) describes what looks like a similar situation.

You could also try installing into a virtualenv, since there could be something going on with your global environment (I didn't think openssl was required on windows).

**Comment by bulletfreak** [comment]
1. Install Win32 OpenSSL.

2. Go Tools > Options... In Options dialog Directories tab. Select category Include files. Add "<OpenSSL installed dir>\include" here, for example "C:\OPENSSL-WIN32\INCLUDE".

That's obliviously just for that specific program. I added OpenSSL in the environment variables
[http://i.imgur.com/noHgXX3.png](url)

**Comment by simon-weber** [comment]
Hm. Have you restarted your shell since then? Path updates won't take effect until a restart, I think.

**Comment by bulletfreak** [comment]
I did, and got the same error :(

**Comment by simon-weber** [comment]
Huh! Sorry, not sure what else to try :confused:

**Comment by bulletfreak** [comment]
You said to make a virtual environment? I guess I should try that

**Comment by thebigmunch** [comment]
Yeah, if you run into this, you'll need to download and install OpenSSL for Windows (https://slproweb.com/products/Win32OpenSSL.html for one installer).

I don't know why this is happening, since pip should install the statically linked wheels rather than compiling. There's nothing to do in gmusicapi for this as far as I can tell.
