### ISSUE TITLE
improve Mobileclient.get_all_stations() docs

### ISSUE THREAD

**Issue by gtzogana** [simon-weber/gmusicapi#471]
It's not quite clear what this method returns. Is it all radio stations played by the user?

**Comment by gtzogana** [comment]
Seems that's what it is. Might be worth adding to the docs.

**Comment by simon-weber** [comment]
Huh, yeah, I haven't looked into this since it was added, which was when stations were a first-class thing that the user created and maintained like playlists.

**Comment by gtzogana** [comment]
In that case, it might also be worth extending the radio station access in general. I threw together a basic radio track scraper last night, and currently the only way to grab the station of interest is to play it and then take it out of the 'last played' dictionary.

I could do it, but it'll take me a while to figure out, unless you have any thoughts on how to go about it.

**Comment by thebigmunch** [comment]
> Seems that's what it is. Might be worth adding to the docs.

You don't actually have to play them. When subscribed, stations you listen to are added automatically, but there's also an option to add a station to your library without listening even without a subscription. It would probably be worth looking to see if there's an endpoint for that so it could be added to gmusicapi.

> In that case, it might also be worth extending the radio station access in general.

gmusicapi is stuck with what functionality Google provides through endpoints. There's a fair amount that the mobile app provides that is done client-side which, in the case of gmusicapi users, means it would be done in user code. So, if it's something that exists in the Google Music API, it could be added. Otherwise, we're out of luck.

> I threw together a basic radio track scraper last night, and currently the only way to grab the station of interest is to play it and then take it out of the 'last played' dictionary.

Have you tried using Mobileclient.search to find the station?
