### ISSUE TITLE
import gmusicapi seems to break str.intern on Python 2.7.9

### ISSUE THREAD

**Issue by tkem** [simon-weber/gmusicapi#493]
Full story:
https://github.com/mopidy/mopidy-gmusic/issues/143
https://github.com/mopidy/mopidy/issues/1550

Here in Mopidy-land, we're a little puzzled with an issue that seems to arise when using `mopidy-gmusic`. I've tracked down this to the point where it seems that a simple
```
import gmusicapi
```
actually changes the `bytes` type to be a _subclass_ of `str`, which happens to break `intern(bytes)`.  This *may* be a side-effect of using the`future` module, but your help with thus would be greatly appreciated.
To make things more interesting, this only seems to be an issue with Debian/Raspbian "Jessie", but not for example with Ubuntu 16.04.

**Comment by simon-weber** [comment]
Huh, that's an odd one. It looks like the future folks are the ones to talk to. Here's output from 2.7.11 on osx with future==0.15.2:
```python
>>> intern(bytes('foo'))
'foo'
```
```python
>>> from builtins import bytes, str
>>> intern(bytes('foo'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't intern subclass of string
```

Hopefully they'll know whether this is a bug or just something that isn't allowed in 2/3 codebases (I have no idea how intern works in py3k, haha).

**Comment by thebigmunch** [comment]
The problem isn't with intern itself. It's that on Python 2, the fields from gmsucicapi would be ``newstr``, which intern can't handle. I don't believe this is an issue actually caused by just importing gmusicapi. But I haven't taken any kind of in-depth look.

The ``intern`` function appears to be used in just one place (https://github.com/mopidy/mopidy/blob/master/mopidy/models/fields.py#L101) in mopidy. It'd be pretty simple to to do a try/except there for a TypeError to work around things for now or even just a call to ``compat.text_type`` to convert it for the ``intern`` call. If this is caused by something originating in mopidy-gmusic, it might be best to fix it on that end. But I don't know those codebases.

PS If @simon-weber let me, I'd rip out python-future (and Python 2 support with it) from gmusicapi. The code would love it, and so would I. That'd "fix" the problem ^_^

**Comment by thebigmunch** [comment]
And reading the mopidy issue linked, it seems you already figured out as much about always interning str/unicode.

**Comment by tkem** [comment]
@simon-weber, @thebigmunch: Thanks for looking into this! As I said before, I'm a little lost here, knowing nothing about `gmusicapi` and/or `future`...

However, in the mean time I was able to boil it down to this:
```
>>> import gmusicapi
>>> from mopidy.m3u import translator
>>> type(translator.path_to_uri(b'foo'))
<class 'future.types.newstr.newstr'>
```
Whereas, without `gmusicapi`:
```
>>> from mopidy.m3u import translator
>>> type(translator.path_to_uri(b'foo'))
<type 'unicode'>
```
So my question is, how can the `future` types "leak out" to other modules by simply `import`ing gmusicapi?

**Comment by tkem** [comment]
OK, so I think I finally figured it out: `gmusicapi` uses the standard library "aliases" from `future` quite a lot:
```
from future import standard_library
standard_library.install_aliases()
```
AFAICS, this installs (among other things) a backported version of `urllib.parse`, that returns `future`'s `newstr` type. The issue I'm having with is that this `urllib.parse` module is now available _globally_, so other modules that perform their own Py2/Py3 compatibility layer like so
```
try:
    from urllib.parse import quote_from_bytes, unquote_to_bytes
except ImportError:
    # Py2 compatibility functions here
```
will get the `future` types, too.  So I'm wondering whether using `install_aliases()` in a _module_ is actually a good idea. In an application, okay, but changing the runtime environment of other, unrelated modules just by doing an `import` isn't something that I'd recommend. Does the `future` documentation have anything to say about this?

**Comment by thebigmunch** [comment]
I've never run into something specifically like this, because, even when I was working with Python 2/3 compat, I used the 'encode early/decode late` paradigm. So the internals of my code would be using Unicode.

``install_aliases`` is nothing more than that, adding aliases for modules that have moved between Python versions; it changes nothing about the modules themselves. The full backports are a [seperate thing](http://python-future.org/imports.html#included-full-backports).

As you said, this isn't happening on all distros tested. I can't reproduce the behavior on any of my systems. No offense, but you keep throwing the "blame" on something when it's not even clearly showing that's where it belongs. So I'm wondering if you've gotten other people to test on those distros to see if it's just certain systems or all of them. It's certainly too early to wonder if ``install_aliases`` should be used in modules. This behavior should be brought up on the ``python-future`` issue tracker to see if they can explain it. I definitely haven't looked at most of the internals of python-future, so maybe there's something there.

**Comment by thebigmunch** [comment]
On a related note to my last comment, have you tried starting fresh with your Python installs on those systems showing this behavior? Does this happen in clean virtualenvs on those systems?

**Comment by tkem** [comment]
I wasn't intending to "blame" anybody, no offense meant! I'm just puzzled by the fact a simple `import` of one module seems to change behavior of another, completely unrelated module, and since I'm not familiar with `future`, I was asking if you knew of any issues usage of `install_aliases` might have in such a setting.

**Comment by thebigmunch** [comment]
No offense was taken. I was just pointing out that it's far too early and there's far too little evidence to even start thinking this is an issue in python-future at large. Pontificating that here is kinda pointless for now, since asking the python-future devs would be the best way to see if that's even possible. Until then, the best options for figuring things out is what I suggest above to see if it's a problem on more than just a small set of systems.

Get other people to test on those specific distros and different versions of those distros to see if it's system-specific instead of distro-specific. Then start fresh on those systems (maybe take a fresh VM for a spin) and use virtualenvs to test things. That should help figure out if there's something on those specific distros/systems that's causing something wonky. It wouldn't be the first time.

**Comment by thebigmunch** [comment]
And I forgot, you could also compile Python in userland to bypass the system-installed Python. This will help eliminate the possibility of something going on with the system Python and help test multiple versions on the same system.

I'm interested in hearing the results of all these tests/experiments.

**Comment by simon-weber** [comment]
Nice digging in https://github.com/simon-weber/gmusicapi/issues/493#issuecomment-244304645, @tkem. I was also puzzled how you could get new types as a result of install_aliases, since it looked like that didn't touch the python 2 import paths.

I'll open an issue with the future folks to see what they have to say. At this point, it does look like install_aliases is something libraries should avoid (in the same way they'd want to avoid eg gevent's monkeypatching, though the effect is much more subtle).

In the meantime, if someone feels like looking into what it'd take to remove install_aliases, that'd be super helpful. I'm hoping it'd be as easy as manually importing a few future modules instead of the stdlib, but there's a chance that we depend on eg stdlib importing the stdlib aliases.

**Comment by thebigmunch** [comment]
Just a note, I did finally reproduce this behavior on one of my systems..

Anyway, I'll take a look at what would be needed to remove ``install_aliases`` in gmusicapi in case that's required. IIRC, it isn't much and ``install_aliases`` was used more so committers didn't really need to be aware of anything more than having to write proper Python 3 code.

**Comment by tkem** [comment]
Thanks for bearing with me and looking into this! Now that I have a rough idea what might be going on, it should be rather easy to add some workarounds to mopidy-m3u so it no longer conflicts with gmusicapi.

**Comment by thebigmunch** [comment]
@tkem: I'd make them provisional if you do. If the python-future devs do find and fix the issue, there'd be no real need. And if it turns out not to be the case, it'd actually be easy to remove ``install_aliases`` usage from gmusicapi. In fact, I've already done it and just been too lazy to run the tests to make sure everything still works properly and that it eliminates the issue.

**Comment by tkem** [comment]
@thebigmunch: sounds great!  Thanks!

**Comment by tkem** [comment]
Thank you  very much!
