### ISSUE TITLE
wma upload support

### ISSUE THREAD

**Issue by rumpeltux** [simon-weber/gmusicapi#512]
Thanks for the great piece of software. I was struggling to upload stuff with the chrome plugin since forever. Major pita, but gmusicapi works like a charm! :)

I was successfully able to upload wma files by adding '.wma' to constants.py:SUPPORTED_SONG_FORMATS

Should this be added by default?
Or should there be a way to override this using commandline flags?
Or should MM try to query which formats are supported by avconv/ffmpeg?

**Comment by thebigmunch** [comment]
You must be talking about my [gmusicapi-wrapper](https://github.com/thebigmunch/gmusicapi-wrapper) package (probably though using my [gmusicapi-scripts](https://github.com/thebigmunch/gmusicapi-scripts) package), not gmusicapi. And the reason I don't support support WMA in gmusicapi-wrapper is because mutagen does not support WMA through its ``easy=True`` interface, which would add significant complexity to the metadata filtering functionality for a very small return.

gmusicapi itself supports WMA uploading just fine.

**Comment by rumpeltux** [comment]
Yes, you’re right, sorry for filing in the wrong project.
I haven’t read through all the source, but looks like mutagen is used for metadata filtering. For the simple case of using gmupload without filters it might make sense to allow using wma files then. Feel free to close if you don’t agree or this is more complicated.

**Comment by simon-weber** [comment]
No problem. Looks like there's nothing to change on this end, so I'm gonna close this. Feel free to reopen on https://github.com/thebigmunch/gmusicapi-wrapper.
