### ISSUE TITLE
include_deleted unexpectedly removed

### ISSUE THREAD

**Issue by soncaokim** [simon-weber/gmusicapi#533]
Hello,

I'm wrapping the gmusicapi in a script that synchronize the cloud library with the local library. 
Among other things, this scripts detects songs that have been deleted on the cloud and delete them locally.

The 10.1.1 version has deprecated(?) the include_deleted option, and my script is not working any more. 

Are you planing to introduce this back, or this will be removed completely? In the latter case, what will be the mean to obtain deleted songs from the cloud?

Thanks in advance, 

Son

**Comment by simon-weber** [comment]
Sorry to pull the rug out from under you! Removing support was a quick fix for the performance problems caused by min-updated=0 over in https://github.com/simon-weber/gmusicapi/issues/513. It probably warranted a major version increase; my bad.

I'm planning to fully remove that flag eventually. However, I'll be adding support back for your use case by exposing min-updated directly. That way you could store the datetime of your last sync and just request changes since then on your next one. https://github.com/simon-weber/Autoplaylists-for-Google-Music and Google's own clients pull updates this way.

**Comment by soncaokim** [comment]
Hi Simon, thanks for the reply. Yeah, the breaking change warranted a
bigger warning :-)

Do you have any crisp example how to query deleted items (or deleted items
since last christmas)? Or I have to dig the chrome extension provided?

Son

**Comment by simon-weber** [comment]
I was about to suggest calling directly into the lower level code, but that'd be painful since you'd need to handle paging the response yourself.

I'll try to make time for adding support for arbitrary datetimes in the next week or so. In the meantime, I'd just suggest reverting to the previous version.

**Comment by soncaokim** [comment]
Thanks for that.

Son

**Comment by soncaokim** [comment]
Hi Simon, do you have any update on this front? Or anything I can help to
move this forward?

Thanks

S

**Comment by simon-weber** [comment]
Whoops, sorry to leave you hanging! I should have time this weekend -- for real this time!

**Comment by simon-weber** [comment]
This turned out to be much easier than I thought! All the code was there already to support it, I just had to expose it.

Grab the develop version and see if it works for you.

**Comment by soncaokim** [comment]
Hi Simon,

I did not have time to check this. Will do this weekend.

Thanks for the great support.

Son

**Comment by soncaokim** [comment]
It works. Thank Simon.

--

For those who shares the need to get deleted songs via this API:

trashRetentionDays = 60 # Google advertize a 60 days window...
trashRetentionDays = trashRetentionDays * 1.25 # ...but it's often more than that

backlog = datetime.datetime.now() - datetime.timedelta(days=trashRetentionDays)

api.get_all_songs(incremental=True, updated_after = backlog)

>

**Comment by simon-weber** [comment]
Great! Sorry it took so long, haha.
