### ISSUE TITLE
Retrieving/generating Mobileclient.FROM_MAC_ADDRESS fails

### ISSUE THREAD

**Issue by uahim** [simon-weber/gmusicapi#556]
example code 
```
from gmusicapi import Mobileclient
print(Mobileclient.FROM_MAC_ADDRESS)
```
and this is what it prints on the console:

```
$ python mac.py
<object object at 0x03B4F030>
```

ideas? :-)
thanks

**Comment by simon-weber** [comment]
That's the expected behavior: that property is just an arbitrary sentinel object (which you can see [here](https://github.com/simon-weber/gmusicapi/blob/522487fde35fe5ff6e0be3de2e4ac70651a6b46c/gmusicapi/clients/mobileclient.py#L28)).

What are you trying to do? Or, similarly, what did you expect that to print?

**Comment by uahim** [comment]
apologies

**Comment by simon-weber** [comment]
Haha, no worries. Feel free to make doc suggestions if there's something to prevent misunderstandings.
