### ISSUE TITLE
sorting by bitrate

### ISSUE THREAD

**Issue by vistamon82** [simon-weber/gmusicapi#557]
hello,

since only musicmanager.py's code has any mention of bitrate, how would i be able to use it to produce a list of every track title i have in my library, sorted by bitrate?

thanks

**Comment by simon-weber** [comment]
I'm not sure that metadata is actually available through gmusicapi: the music manager only deals in it when sending upload requests, and Google doesn't provide it through the mobile apis.

https://autoplaylists.simon.codes supports this, though, since it uses the web apis that gmusicapi doesn't. If you're only interested in exporting a list (and not creating a playlist), you can use the [debugging interface](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#manually-making-queries) and export the results to csv.

**Comment by thebigmunch** [comment]
Using the mobileclient, you can use the ``durationMillis`` and ``estimatedSize`` keys to calculate the bitrate for tracks, though.

**Comment by vistamon82** [comment]
thanks @simon-weber. i downloaded your autoplaylists extension and i will try getting a list of my songs from there. any tips on doing so?

**Comment by vistamon82** [comment]
never mind, i figured it out
![image](https://user-images.githubusercontent.com/13377663/26954796-1f29b4a2-4c67-11e7-9a20-629d1a259e7b.png)

thanks @simon-weber and @thebigmunch

**Comment by simon-weber** [comment]
Great! Glad it worked for you.
