### ISSUE TITLE
404 Error =>Fetchtrack

### ISSUE THREAD

**Issue by blackarcanis** [simon-weber/gmusicapi#595]
Since some weeks ago, I've got now a 404 Not found when I do a simple "fetchtrack" method.
For example:
https://mclients.googleapis.com/sj/v2.5/fetchtrack?hl=fr_FR&tier=aa&dv=6322&client-build-type=prod&alt=json&nid=Thgggyakfla4ypu4shoqmg5id24

The same request made from my android device and loged thanks Fiddler working well...

Do you have same issue with "fetchtrack" ?

**Comment by simon-weber** [comment]
Usually for store tracks this is just due to wonkiness on Google's end, since they change the ids unexpectedly. Is it still broken? If so, it might be a sign of larger issues, since this is a bit similar to the discussion at https://github.com/simon-weber/gmusicapi/issues/594 (but for a different endpoint).

**Comment by blackarcanis** [comment]
Yes always the issue unfortunately :/
I use this method when I want to set a rating for a track, I need to get complete metadatas first.

**Comment by blackarcanis** [comment]
My bad,
Request working well, it was an issue with my CURL request in PHP !
Sorry for this, I'm closing this thread.

**Comment by simon-weber** [comment]
No worries. Glad you got it sorted out.
