### ISSUE TITLE
Info about a track in a playlist

### ISSUE THREAD

**Issue by LuigiSigillo** [simon-weber/gmusicapi#657]
If you have a playlist that contains songs updated by you, it is not possible to see complete information about the songs. I mean that when I iterate over the song of a playlist I can not have info like artist album and title. What can I do with the track ID if I cannot search with this ID other info about a song?

**Comment by simon-weber** [comment]
You're referring to songs with a store id, right (which is needed for [get_track_info](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_track_info))? I don't think there's a good solution: Google just doesn't send that information to mobile clients for whatever reason.

It's possible to retrieve that information from the web client ([eg](https://github.com/simon-weber/Autoplaylists-for-Google-Music/blob/25efa46bbb6815eaf3cba69122c308f5f05257bd/src/js/googlemusic.js#L54)), but because of the auth situation that doesn't really work outside the context of a Chrome Extension.

**Comment by LuigiSigillo** [comment]
Hi, probably I have not written clearly what I was asking for. However I have found a solution to my problem:
```python
songs = mc.get_all_songs()
def get_songs_info(id_song):
    for e in songs:
        if e['id'] == id_song:
            return {
                "title": e['title'],
                "artist": e['artist'],
                "album": e['album']
            }

def get_songs_of_playlist(playlist_name):
    playlists = mc.get_all_user_playlist_contents()
    for p in playlists:
        p_dict_list = []
        if playlist_name == p["name"]:
            for track in p['tracks']:
                p_dict_list.append(get_songs_info(track['trackId']))
            return p_dict_list
```
Maybe it's more clear with the code than with my words, but I'm referring to songs that I have personally uploaded on Google Play Music.
My problem was to find information (title, artist etc.) about the songs contained inside a playlist. To do this I have first downloaded all the songs and then search every time with the **trackId** present inside the playlist. 
My suggestion was to provide not only the trackId but also this other useful information inside a playlist dictionary, but for what I'm understanding now, this is not possible due to some Google policy. So I think this may be a good solution to achieve my purpose, otherwise let me know if there is something to improve in this solution or am I using the client in some wrong way.
Thank you.

**Comment by simon-weber** [comment]
Ah, yes, I see what you're getting at. User-uploaded song metadata isn't provided inline in playlist responses; it needs to be looked up from the results of get_all_songs. Presumably Google made the apis this way since their own clients are pretty heavy (they run their own databases and everything).

There's some old discussion of this in https://github.com/simon-weber/gmusicapi/issues/232#issuecomment-43887144. I'm more hesitant to automatically do the matching these days since these kinds of relationships happen in a few places and I'd rather not be inconsistent. Updating the docs to explain the situation would be good, though.
