### ISSUE TITLE
Using dynamic oauth_filepath in Mobileclient

### ISSUE THREAD

**Issue by fergyfresh** [simon-weber/gmusicapi#658]
So I'm currently trying to use this on an AWS serverless deployment and the device id stuff works great locally, but when i try to deploy it i'm trying to force it passed the initial login phase since Lamba functions aren't persistent, so I wanted to see if the mobileclient.cred file with the device_id was good enough.

I'm still working through it, but I can't figure out how to bypass the Mobileclient.oauth_login with the OAUTH_FILEPATH being non-default. I tried to overwrite the instance variable upon declaration, but that didn't seem to work.

The tl:dr is that lambda functions don't have write access to the home directory and that is where `appdirs` decides to dump your stuff, so i went down the rabbit hole of having to manually override the `OAUTH_FILEPATH` in the Mobileclient and the shared modules, but I don't think I overrode it deep enough, because when I copied the contents of the file to `/tmp/mobildclient.cred` and overrode all of the filepaths from the `appdirs` ones it still doesn't work. 

I can provide follow up answers to anyone that wants to help me debug and needs more infoz.

**Comment by simon-weber** [comment]
I'd recommend not using the filesystem at all and just passing an Oauth2Credentials directly. Last time I checked Google didn't provide an easy way to create one from a secret directly but I made one since the tests work this way: https://github.com/simon-weber/gmusicapi/blob/f6bd1120badfde68887da891666ab73966e4396a/gmusicapi/session.py#L31

If you extract a refresh token from a .cred file you've created earlier, then you can do something like:
```python
from gmusicapi import session, Mobileclient
credentials = session.credentials_from_refresh_token(refresh_token, session.Mobileclient.oauth)
Mobileclient.oauth_login(oauth_credentials=credentials, device_id='...')
```

If it's helpful, the test code example is here: https://github.com/simon-weber/gmusicapi/blob/f6bd1120badfde68887da891666ab73966e4396a/gmusicapi/test/run_tests.py#L80. That code is a bit peculiar though; yours should be able to be much simpler.

**Comment by fergyfresh** [comment]
Thanks, this worked locally, but on Lambda it keeps logging out.

```
1577136284178] 2019-12-23 21:24:44,177 - gmusicapi.Mobileclient1 (shared:80) [INFO]: initialized
[1577136284178] [INFO] 2019-12-23T21:24:44.177Z 934bc3e3-8853-47b2-ad4f-8ac3b2f78610 initialized
[1577136284178] 2019-12-23 21:24:44,178 - gmusicapi.Mobileclient1 (shared:104) [INFO]: logged out
[1577136284178] [INFO] 2019-12-23T21:24:44.178Z 934bc3e3-8853-47b2-ad4f-8ac3b2f78610 logged out
[1577136284181] [INFO] 2019-12-23T21:24:44.181Z 934bc3e3-8853-47b2-ad4f-8ac3b2f78610 Refreshing access_token
```

Code looks like this:
```
device_id = # a valid device id
refresh_token = # refresh token from the .cred file
api = Mobileclient()
credentials = session.credentials_from_refresh_token(refresh_token, session.Mobileclient.oauth)
success = api.oauth_login(oauth_credentials=credentials, device_id=device_id)
```

This works locally, but bombs out in the AWS Lambda.

**Comment by simon-weber** [comment]
Ah, Google is probably restricting the login because it's suspicious of the ip. Sometimes logging in manually from the ip is enough to whitelist it going forward, but you'll have a hard time doing that from lambda.

I don't think there's an easy fix. You could run it from a vpc and set up a NAT, but that might be overkill. Or, if you have another machine handy with a static ip, you could proxy through it.

I don't think there's much about the oauth code on our end to change - last time I checked, the scope we need isn't given out to custom apps - but it's possible there's a string to pull on there as well.

**Comment by fergyfresh** [comment]
If it works locally, but not on the Lambda i'm assuming its not a scope issue though. It wouldn't make sense to work on one computer and not on the other because of auth scopes right? The IP part makes sense, it probably doesn't like that I'm using a refresh token from one IP on another IP without going through the auth flow again.

**Comment by simon-weber** [comment]
Ah, yeah, what I mean is that the added ip suspicion may be a result of the urn:ietf... local redirect, which is the only one Google's OAuth app permits. Making our own and setting up web redirects might fix that - [Autoresponder](https://gchat.simon.codes/) has worked without issues despite me running it on various hosts - but Google doesn't allow adding the skyjam scope to new Oauth apps. So, we're stuck with whatever is set on the one they're using.

**Comment by fergyfresh** [comment]
What does Autoresponder run on for infrastructure? 

The other piece that's annoying is the regular login stopped working from Lambda, but also still works locally. 

Zzzz. Thanks for helping troubleshoot though.

**Comment by simon-weber** [comment]
It's on GCP currently. I've run it on ec2 in the past.

Right, you want the refresh token for anything long-lived. The access token is what's actually sent to auth calls, but it expires relatively quickly.

**Comment by fergyfresh** [comment]
Yeah the Lambda thing was more of an experiment anyway. It's just a shame I might have to sunset it, I guess we can close this thread as you've gotten me passed my initial blocker, its just unfortunate now its hanging on an archived dep of this project :(

https://github.com/googleapis/oauth2client/blob/0d1c814779c21503307b2f255dabcf24b2a107ac/oauth2client/client.py#L777-L780
