### ISSUE TITLE
Value Error :(

### ISSUE THREAD

**Issue by himanshujaidka** [simon-weber/gmusicapi#671]
While setting up an environment it shows value error. What's the solution to overcome it?

**Comment by himanshujaidka** [comment]
This will help you to understand
![value error](https://user-images.githubusercontent.com/58654018/88519424-ba7c0c00-d00f-11ea-9d0e-5d544db9db4b.png)

**Comment by simon-weber** [comment]
To run the tests you'll need to set environment variables so that the tests are able to log into your accounts. The best place to see what is expected is in https://github.com/simon-weber/gmusicapi/blob/develop/gmusicapi/test/run_tests.py.

The tests are kind of a pain in the ass, though, so I wouldn't bother with them unless you're planning to work on something significant.

**Comment by himanshujaidka** [comment]
ok, I will work on some other issue
